# Generated by Django 4.2.7 on 2023-11-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_category_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='introducao',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
