# Generated by Django 4.2.7 on 2023-12-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_introducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='ew', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
